FROM lasuite/impress-frontend@sha256:c9dee7dc1ca578ce1aad919b38752b25ea89424b605159811546e3b94a15a7f4

LABEL org.opencontainers.image.title="LaSuite Docs Y-Provider Image"
LABEL org.opencontainers.image.description="LaSuite Docs Y-Image Image preconfigured for FSBCG."
LABEL org.opencontainers.image.authors="Martin Bens <martin.bens@uni-bayreuth.de>"

LABEL org.opencontainers.image.source="https://github.com/fsbcg-ubt/lasuite-docs"
LABEL org.opencontainers.image.version="v3.10.0"
LABEL org.opencontainers.image.licenses="MIT"

LABEL org.opencontainers.image.base.name="registry.hub.docker.com/lasuite/impress-backend"
LABEL org.opencontainers.image.base.digest="sha256:f170c156e1867ec088248b2341f315c48312375a1ad6fa8ff64cc43941b9a937"

LABEL maintainer="Martin Bens <martin.bens@uni-bayreuth.de>"
LABEL lasuite_docs_version="v3.10.0"

# Logging Configuration
ENV COLLABORATION_LOGGING=true